### ISSUE TITLE
stuck on create channel

### ISSUE THREAD

**Issue by SaifRehman** [swetharepakula/fabric-evm-ibm-container-service#1]
error cant create channel
stuck here: Flag --show-all has been deprecated, will be removed in an upcoming release
Waiting for createchannel container to be Completed

**Comment by SaifRehman** [comment]
so go has to be installed to deploy to kubernetes?

**Comment by swetharepakula** [comment]
Solved off line. Problem was deployment on a multi node cluster. This deployment expects only a single node cluster.

**Comment by hskang9** [comment]
I did this on single cluster and the problem persists. Can you give me reason why?

**Comment by hskang9** [comment]
the error is because of the access level
https://stackoverflow.com/questions/56181204/0-sub-policies-were-satisfied-but-this-policy-requires-1-of-the-writers-sub-p

**Comment by hskang9** [comment]
The error happened here: `kubectl logs createchannel createchannel`

**Comment by swetharepakula** [comment]
The original issue on the multi node cluster was because certs were stored in a volume on a particular node and so pods on other nodes could not find them.

In your case if you are getting a policy problem that means that something is not right with your certs. I would verify that your PVC has the all the certs and that createchannel can see those certs.

**Comment by hskang9** [comment]
Thank you for your answer. Is there any troubleshooting section for setting up certs between PVC and createchannel pod?

**Comment by hskang9** [comment]
I have run the command `kubectl cp <pod name>:/shared/crypto-config crypto-config` and checked that each node has the other nodes' certs, so it seems that createchannel cannot see them. Is this because I am using free version of ibm cloud cluster?
